import random

newUser = 'y'
users = []


while newUser == 'y': 
    user = {}


    firstName = input('Please enter your first name: ').lower()
    lastName = input('Please enter your last name: ').lower()
    email = input('Please enter your email address: ')


    alphabets = 'abcdefghijklmnopqrstuvwxyz'
    randomString = ''
    for i in range(5):
        randomString += alphabets[random.randint(0, len(alphabets) - 1)]
    password = firstName[:2] + lastName[-2:] + randomString
    print('This is your autogenerated password: ' + password)
    selectionOptions = ['n', 'y']
    passwordSatisfaction = input('Are you satisfied with this password? (Y)es or (N)o: ').lower()
    while passwordSatisfaction not in selectionOptions:
        print('Wrong input!')
        passwordSatisfaction = input('Are you satisfied with this password? (Y)es or (N)o: ').lower()
    if passwordSatisfaction == 'n':
        password = input('Please enter your chosen password: ')
        if len(password) < 7:
            print('Password must be equal to or greater than 7 in length!')
            password = input('Please enter your chosen password: ')


    user['firstName'] = firstName.capitalize()
    user['lastName'] = lastName.capitalize()
    user['email'] = email
    user['password'] = password
    users.append(user)


    newUser = input('Would you like to add another user? (Y)es or (N)o: ').lower()
    while newUser not in selectionOptions:
        print('Wrong input!')
        newUser = input('Would you like to add another user? (Y)es or (N)o: ').lower()


for user in users:
    print('User Firstname: ' + user['firstName'])
    print('User Lastname: ' + user['lastName'])
    print('User Email: ' + user['email'])
    print('User Password: ' + user['password'])
    print('******************************')
